version: '2'
services:
    jhipstersa2-app:
        image: jhipstersa2
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhipstersa2-mysql:3306/jhipstersa2?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipstersa2-mysql:
        extends:
            file: mysql.yml
            service: jhipstersa2-mysql
